Importing important libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

 Loading the dataset to a dataframe

In [3]:
Credit_card_data = pd.read_csv('/content/creditcard.csv')

Data Reading & Cleaning

In [4]:
# Listing first 5 rows of the dataset
Credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
# Listing last 5 rows of the dataset
Credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [6]:
# Retrieving dataset information
Credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
# Checking the number of missing values in each column
Credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

Thus, there are no any data/ column entry that is missing.

In [8]:
# distribution of legit transactions & fraud transactions
Credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In the above table, 0 represents normal transactions, while 1 represents fraudulent transations.

As the given data is highly unbalanced, we need to separate the two classes of transactions.

In [9]:
# Separating the datasets into classes: 'legit' and 'fraud' for analysis:
legit = Credit_card_data[Credit_card_data.Class == 0]
fraud = Credit_card_data[Credit_card_data.Class == 1]

In [10]:
#checking shape(rows, columns) for both class:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [11]:
# Finding out statistical measures of the data:
#First, for legit class:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
#Similarly, for fraud class:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [13]:
# Comparing the values for both transactions
Credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

**Under-Sampling**

To build a sample dataset containing similar distribution of normal transactions and fraud transactions

As number of fraud transactions = 492

For similar distribution, taking a sample of 492 legit transactions.

In [14]:
legit_sample = legit.sample(n=492)

*Concatenating* two DataFrames

In [15]:
New_dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
# Listing first 5 rows of the new dataset
New_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
27829,34721.0,0.884120,0.392987,1.150932,3.817077,-0.104372,0.804389,-0.087168,0.303968,-1.172281,...,-0.158941,-0.540805,0.086525,0.178408,0.197405,-0.192830,0.008465,0.030038,69.95,0
29505,35500.0,-0.916277,-0.675210,2.165419,-1.475604,-0.188210,-0.678149,-0.961709,0.317053,1.453892,...,0.281710,0.630436,-0.297735,-0.428948,0.199142,0.358044,0.079037,0.090193,1.00,0
129,81.0,1.111048,0.215352,0.374073,1.150001,-0.329768,-0.898688,0.309907,-0.255277,-0.110655,...,-0.132555,-0.493867,-0.010782,0.380389,0.456214,-0.572347,0.010981,0.039295,68.74,0
122062,76421.0,-0.648578,-0.176993,0.594644,-4.469813,-0.298344,-0.863875,0.951863,-0.218345,-0.003957,...,-0.153128,0.235678,-0.212519,0.035464,0.212174,-1.041461,0.070479,0.111036,74.73,0
205586,135824.0,-0.579230,0.858271,-1.531827,-0.585866,0.946221,-0.457928,1.218981,-0.241070,0.092773,...,0.225477,0.855908,-0.281228,0.006898,-0.193270,-0.287277,-0.488740,-0.246904,112.50,0

In [17]:
# Listing the last 5 rows of the new dataset
New_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [18]:
#Checking the no. of rows of fraud and legit transactions in the new dataset.
#Both should be same and =492.
New_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [19]:
# Again, comparing the values for both transactions for this new dataset
New_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94610.947154,0.007877,-0.031323,0.020829,0.060829,-0.118458,-0.080200,-0.029887,0.029130,-0.034302,...,-0.018731,-0.017239,0.003066,-0.014573,0.038233,-0.000256,0.007764,0.030889,-0.006585,98.709715
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data into Features(X) & Targets(Y)

In [20]:
X = New_dataset.drop(columns='Class', axis=1)
Y = New_dataset['Class']

In [21]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
27829    34721.0  0.884120  0.392987  1.150932  3.817077 -0.104372  0.804389
29505    35500.0 -0.916277 -0.675210  2.165419 -1.475604 -0.188210 -0.678149
129         81.0  1.111048  0.215352  0.374073  1.150001 -0.329768 -0.898688
122062   76421.0 -0.648578 -0.176993  0.594644 -4.469813 -0.298344 -0.863875
205586  135824.0 -0.579230  0.858271 -1.531827 -0.585866  0.946221 -0.457928
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
27829  -0.087168  0.303968 -1.172281  ... -0.079346 -0.158941 -0.540805
29505  -0.961709  0.317053  1.453892  ...  0.249810  0.281710  0.630436
129     0.309907 -0.255277 -0.110655  ...  0.031672 -0.132555 -0.493867
122062  0.951863 -0.218345 -0.003957  ... -0.657532 -0.153128  0.235678
205586  1.218981 -0.241070  0.092773  ... -0.315161  0.225477  0.855908
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
27829   0.086525  0.178408  0.197405 -0.192830  0.008465  0.030038   69.95
29505  -0.297735 -0.428948  0.199142  0.358044  0.079037  0.090193    1.00
129    -0.010782  0.380389  0.456214 -0.572347  0.010981  0.039295   68.74
122062 -0.212519  0.035464  0.212174 -1.041461  0.070479  0.111036   74.73
205586 -0.281228  0.006898 -0.193270 -0.287277 -0.488740 -0.246904  112.50
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [22]:
print(Y)

27829     0
29505     0
129       0
122062    0
205586    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Splitting the data into Training data & Testing Data

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [24]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

**Model Training & Evaluation**

In [25]:
#Initializing models
Models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

In [26]:
# Training the models
# Then, predicting using X_test dataset and finally calculating accuracy

results = []

for name, model in Models.items():
    model.fit(X_train,Y_train)
    Y_pred = model.predict(X_test)
    accuracy = accuracy_score(Y_test, Y_pred)
    precision = precision_score(Y_test, Y_pred)
    recall = recall_score(Y_test, Y_pred)
    f1 = f1_score(Y_test, Y_pred)
    results.append({
        "Model": name,
        "Accuracy": round(accuracy * 100, 2),
        "F1 Score": round(f1 * 100, 2),
        "Precision": round(precision * 100, 2),
        "Recall": round(recall * 100, 2)
      })

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

*Results Table*

In [27]:
# Display results as a DataFrame
df_results = pd.DataFrame(results)
print(df_results)

                 Model  Accuracy  F1 Score  Precision  Recall
0  Logistic Regression     94.42     94.12      98.88   89.80
1        Decision Tree     89.85     89.47      92.39   86.73
2        Random Forest     92.89     92.47      97.73   87.76